# Generated by Django 5.2.2 on 2025-06-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentproof_quantity_paymentproof_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
