# Generated by Django 5.1.6 on 2025-05-20 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_feedhistory_amount_product_service_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingschedule',
            name='feeding_time',
        ),
        migrations.RemoveField(
            model_name='feedingschedule',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='feedingschedule',
            name='portion_size',
        ),
        migrations.RemoveField(
            model_name='message',
            name='color_selected',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='feeding_time1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='feeding_time2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='feeding_time3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='feeding_time4',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='core.product')),
                ('services', models.ManyToManyField(blank=True, to='core.service')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'),
        ),
    ]
