# Generated by Django 5.1.6 on 2025-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_feedingschedule_feeding_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('food', 'Food'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
