# Generated by Django 5.1.6 on 2025-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_category_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('grooming', 'Grooming'), ('training', 'Training'), ('walking', 'Walking'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
