# Generated by Django 5.1.6 on 2025-05-28 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_options',
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedhistory',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
