# Generated by Django 5.2.2 on 2025-06-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
