# Generated by Django 5.1.6 on 2025-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_feedhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('selling', 'Selling'), ('sold', 'Sold')], default='selling', max_length=10),
        ),
    ]
