# Generated by Django 5.2.2 on 2025-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
