# Generated by Django 5.2.2 on 2025-06-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
